description: |
  Build a jar with depstar for deployment to Clojars.
executor: clojurecli
parameters:
  jarname:
    default: "libary"
    type: string
steps:
  - attach_workspace:
      at: /home/circleci
  - run:
      name: Update pom
      command: clojure -Spom
  - run:
      name: Build
      command: clojure -Sdeps '{:deps {seancorfield/depstar {:mvn/version "1.1.116"}}}' "-m" "hf.depstar.jar" "replikativ-<<parameters.jarname>>.jar"
      no_output_timeout: 5m
  - persist_to_workspace:
      root: /home/circleci/
      paths:
        - replikativ/replikativ-<<parameters.jarname>>.jar
