description: |
  Build a jar with depstar for deployment to Clojars.
executor: clojurecli
steps:
  - attach_workspace:
      at: /home/circleci
  - run:
      name: Build
      command: clojure -A:jar
      no_output_timeout: 5m
